-- Migration: Add External Agent Support to Messages Table
-- Date: 2025-11-03
-- Description: Adds support for tracking external agent (like Claude Code) messages
--              with session tracking and agent type identification

-- ============================================================================
-- STEP 1: Add new role type 'ex_agent' to message_role enum
-- ============================================================================

-- Add 'ex_agent' role to the existing message_role enum
-- This role identifies messages generated by external agents (like Claude Code)
-- Distinguished from 'assistant' which is for regular LLM responses

ALTER TYPE message_role ADD VALUE IF NOT EXISTS 'ex_agent';

-- ============================================================================
-- STEP 2: Add external agent tracking fields to messages table
-- ============================================================================

-- Add ex_agent_session_id column
-- This tracks which external agent session created the message
-- Enables session-based queries and conversation forking
-- NULL for non-agent messages (user, assistant, system)

ALTER TABLE messages
  ADD COLUMN IF NOT EXISTS ex_agent_session_id TEXT NULL;

-- Add ex_agent_type column
-- Specifies which type of external agent created the message
-- Values: 'claude_code', or other future agent types
-- NULL for non-agent messages

ALTER TABLE messages
  ADD COLUMN IF NOT EXISTS ex_agent_type TEXT NULL;

-- ============================================================================
-- STEP 3: Add index for efficient session-based queries
-- ============================================================================

-- Create partial index on ex_agent_session_id
-- Only indexes rows where ex_agent_session_id is not NULL (agent messages only)
-- Improves performance for:
--   - Finding all messages in a CC session
--   - Resuming conversations based on session ID
--   - Querying conversation history by agent

CREATE INDEX IF NOT EXISTS idx_messages_ex_agent_session
  ON messages(ex_agent_session_id)
  WHERE ex_agent_session_id IS NOT NULL;

-- ============================================================================
-- STEP 4: (Optional) Add working directory tracking to conversations
-- ============================================================================

-- Add cwd (current working directory) column to conversations table
-- Stores the working directory context for Claude Code sessions
-- Helps maintain proper file path resolution when resuming sessions
-- NULL for conversations that don't use Claude Code

ALTER TABLE conversations
  ADD COLUMN IF NOT EXISTS cwd TEXT NULL;

-- ============================================================================
-- STEP 5: Add composite index for conversation + session queries
-- ============================================================================

-- Create index for efficient queries that filter by both conversation and session
-- Useful for:
--   - Finding specific session messages within a conversation
--   - Conversation branching/forking scenarios
--   - Session-specific message retrieval

CREATE INDEX IF NOT EXISTS idx_messages_conv_session
  ON messages(conversation_id, ex_agent_session_id)
  WHERE ex_agent_session_id IS NOT NULL;

-- ============================================================================
-- VERIFICATION QUERIES
-- ============================================================================

-- Verify the enum was updated
-- Should show: user, assistant, system, ex_agent
-- SELECT unnest(enum_range(NULL::message_role)) AS role;

-- Verify columns were added to messages table
-- SELECT column_name, data_type, is_nullable
-- FROM information_schema.columns
-- WHERE table_name = 'messages'
--   AND column_name IN ('ex_agent_session_id', 'ex_agent_type')
-- ORDER BY column_name;

-- Verify cwd column was added to conversations table
-- SELECT column_name, data_type, is_nullable
-- FROM information_schema.columns
-- WHERE table_name = 'conversations'
--   AND column_name = 'cwd';

-- Verify indexes were created
-- SELECT indexname, indexdef
-- FROM pg_indexes
-- WHERE tablename = 'messages'
--   AND indexname IN ('idx_messages_ex_agent_session', 'idx_messages_conv_session');

-- ============================================================================
-- ROLLBACK SCRIPT (for reference - run manually if needed)
-- ============================================================================

-- WARNING: This rollback will remove the enum value and columns
-- This should only be done if no data exists using the ex_agent role

-- DROP INDEX IF EXISTS idx_messages_conv_session;
-- DROP INDEX IF EXISTS idx_messages_ex_agent_session;
-- ALTER TABLE conversations DROP COLUMN IF EXISTS cwd;
-- ALTER TABLE messages DROP COLUMN IF EXISTS ex_agent_type;
-- ALTER TABLE messages DROP COLUMN IF EXISTS ex_agent_session_id;

-- Note: Removing enum values requires recreating the enum type:
-- 1. Create new enum without 'ex_agent'
-- 2. Alter table to use new enum
-- 3. Drop old enum
-- This is complex and should be avoided if any data uses the enum value

-- ============================================================================
-- USAGE EXAMPLES
-- ============================================================================

-- Example 1: Find all messages in a specific Claude Code session
-- SELECT id, role, content, created_at
-- FROM messages
-- WHERE ex_agent_session_id = 'some-session-id'
-- ORDER BY created_at ASC;

-- Example 2: Get the last Claude Code message in a conversation
-- SELECT id, ex_agent_session_id, content, created_at
-- FROM messages
-- WHERE conversation_id = 'some-conversation-id'
--   AND role = 'ex_agent'
--   AND ex_agent_type = 'claude_code'
-- ORDER BY created_at DESC
-- LIMIT 1;

-- Example 3: Count messages by agent type
-- SELECT ex_agent_type, COUNT(*) as message_count
-- FROM messages
-- WHERE role = 'ex_agent'
-- GROUP BY ex_agent_type;

-- Example 4: Get conversation with its Claude Code working directory
-- SELECT c.id, c.title, c.cwd, COUNT(m.id) as message_count
-- FROM conversations c
-- LEFT JOIN messages m ON m.conversation_id = c.id AND m.role = 'ex_agent'
-- WHERE c.cwd IS NOT NULL
-- GROUP BY c.id, c.title, c.cwd;

-- ============================================================================
-- NOTES
-- ============================================================================

-- 1. RLS Policies: Existing RLS policies on messages table will automatically
--    apply to rows with ex_agent role since they filter by owner_id

-- 2. Triggers: Existing triggers (search vector update, conversation touch)
--    will automatically work with ex_agent messages

-- 3. Backward Compatibility: All changes use IF NOT EXISTS to allow safe
--    re-running of migration. Existing messages are unaffected (NULL values)

-- 4. Session ID Format: No constraints on ex_agent_session_id format.
--    Claude Code SDK uses UUID-like session identifiers

-- 5. Performance: Partial indexes minimize overhead for non-agent messages
--    while optimizing queries for agent messages

-- ============================================================================
-- END OF MIGRATION
-- ============================================================================
